// Generated automatically by nearley, version 2.20.1
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }

const moo = require('moo');

const lexer = moo.compile({
  lparen: '(',
  rparen: ')',
  whitespace: { match: /(?: |(?:\n)|(?:\r)|(?:\t))+/, lineBreaks: true },
  number: /(?:\d+)(?:(?:\.\d+))?(?:[Ee](?:[\+\-])?(?:\d+))?/,
  comma: ',',
  times: '*',
  over: '/',
  plus: '+',
  minus: '-',
  equal: '=',
  differs: '!',
  lessThan: '<',
  greaterThan: '>',
  remainder: '%',
  true: 'true',
  false: 'false',
  not: '!',
  and: '&&',
  or: '||',
  cond: 'if',
  then: 'then',
  thenNot: 'else',
  func: ['abs', 'min', 'max', 'floor', 'sin', 'cos', 'log'],
});

const mathFunctions = new Map(
  Object.getOwnPropertyNames(Math)
    .filter((n) => typeof Math[n] === 'function')
    .map((n) => [n, Math[n]])
);

var grammar = {
    Lexer: lexer,
    ParserRules: [
    {"name": "line$ebnf$1", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "line$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "line", "symbols": ["line$ebnf$1", "conditional"], "postprocess": ([,conditional]) => conditional},
    {"name": "conditional$ebnf$1", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "conditional$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "conditional$ebnf$2", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "conditional$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "conditional$ebnf$3", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "conditional$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "conditional$ebnf$4", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "conditional$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "conditional$ebnf$5", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "conditional$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "conditional", "symbols": [(lexer.has("cond") ? {type: "cond"} : cond), "conditional$ebnf$1", "booleanOr", "conditional$ebnf$2", (lexer.has("then") ? {type: "then"} : then), "conditional$ebnf$3", "booleanOr", "conditional$ebnf$4", (lexer.has("thenNot") ? {type: "thenNot"} : thenNot), "conditional$ebnf$5", "booleanOr"], "postprocess": ([,,cond,,,,fst,,,,snd]) => cond ? fst : snd},
    {"name": "conditional", "symbols": ["booleanOr"], "postprocess": ([booleanOr]) => booleanOr},
    {"name": "booleanOr$ebnf$1", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "booleanOr$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "booleanOr$ebnf$2", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "booleanOr$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "booleanOr", "symbols": ["booleanAnd", "booleanOr$ebnf$1", (lexer.has("or") ? {type: "or"} : or), "booleanOr$ebnf$2", "booleanAnd"], "postprocess": ([fst,,,,snd]) => fst || snd},
    {"name": "booleanOr", "symbols": ["booleanAnd"], "postprocess": ([booleanAnd]) => booleanAnd},
    {"name": "booleanAnd$ebnf$1", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "booleanAnd$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "booleanAnd$ebnf$2", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "booleanAnd$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "booleanAnd", "symbols": ["bool", "booleanAnd$ebnf$1", (lexer.has("and") ? {type: "and"} : and), "booleanAnd$ebnf$2", "bool"], "postprocess": ([fst,,,,snd]) => fst && snd},
    {"name": "booleanAnd", "symbols": ["comparator"], "postprocess": ([comparator]) => comparator},
    {"name": "booleanAnd", "symbols": ["bool"], "postprocess": ([bool]) => bool},
    {"name": "bool$ebnf$1", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "bool$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "bool$ebnf$2", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "bool$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "bool", "symbols": [(lexer.has("lparen") ? {type: "lparen"} : lparen), "bool$ebnf$1", "conditional", "bool$ebnf$2", (lexer.has("rparen") ? {type: "rparen"} : rparen)], "postprocess": ([,,conditional,,]) => conditional},
    {"name": "bool", "symbols": [(lexer.has("true") ? {type: "true"} : true)], "postprocess": ([]) => true},
    {"name": "bool", "symbols": [(lexer.has("false") ? {type: "false"} : false)], "postprocess": ([]) => false},
    {"name": "bool", "symbols": [(lexer.has("not") ? {type: "not"} : not), "bool"], "postprocess": ([,bool]) => !bool},
    {"name": "bool", "symbols": ["fun"], "postprocess": ([fun]) => fun},
    {"name": "comparator$ebnf$1", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "comparator$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "comparator$ebnf$2", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "comparator$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "comparator", "symbols": ["expression", "comparator$ebnf$1", (lexer.has("equal") ? {type: "equal"} : equal), (lexer.has("equal") ? {type: "equal"} : equal), "comparator$ebnf$2", "expression"], "postprocess": ([fst,,,,,snd]) => fst === snd},
    {"name": "comparator$ebnf$3", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "comparator$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "comparator$ebnf$4", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "comparator$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "comparator", "symbols": ["expression", "comparator$ebnf$3", (lexer.has("differs") ? {type: "differs"} : differs), (lexer.has("equal") ? {type: "equal"} : equal), "comparator$ebnf$4", "expression"], "postprocess": ([fst,,,,,snd]) => fst !== snd},
    {"name": "comparator$ebnf$5", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "comparator$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "comparator$ebnf$6", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "comparator$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "comparator", "symbols": ["expression", "comparator$ebnf$5", (lexer.has("lessThan") ? {type: "lessThan"} : lessThan), (lexer.has("equal") ? {type: "equal"} : equal), "comparator$ebnf$6", "expression"], "postprocess": ([fst,,,,,snd]) => fst <= snd},
    {"name": "comparator$ebnf$7", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "comparator$ebnf$7", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "comparator$ebnf$8", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "comparator$ebnf$8", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "comparator", "symbols": ["expression", "comparator$ebnf$7", (lexer.has("greaterThan") ? {type: "greaterThan"} : greaterThan), (lexer.has("equal") ? {type: "equal"} : equal), "comparator$ebnf$8", "expression"], "postprocess": ([fst,,,,,snd]) => fst >= snd},
    {"name": "comparator$ebnf$9", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "comparator$ebnf$9", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "comparator$ebnf$10", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "comparator$ebnf$10", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "comparator", "symbols": ["expression", "comparator$ebnf$9", (lexer.has("lessThan") ? {type: "lessThan"} : lessThan), "comparator$ebnf$10", "expression"], "postprocess": ([fst,,,,snd]) => fst < snd},
    {"name": "comparator$ebnf$11", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "comparator$ebnf$11", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "comparator$ebnf$12", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "comparator$ebnf$12", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "comparator", "symbols": ["expression", "comparator$ebnf$11", (lexer.has("greaterThan") ? {type: "greaterThan"} : greaterThan), "comparator$ebnf$12", "expression"], "postprocess": ([fst,,,,snd]) => fst > snd},
    {"name": "comparator", "symbols": ["expression"], "postprocess": ([expression]) => expression},
    {"name": "expression$ebnf$1", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "expression$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "expression$ebnf$2", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "expression$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "expression", "symbols": ["expression", "expression$ebnf$1", (lexer.has("plus") ? {type: "plus"} : plus), "expression$ebnf$2", "term"], "postprocess": ([fst,,,,snd]) => fst + snd},
    {"name": "expression$ebnf$3", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "expression$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "expression$ebnf$4", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "expression$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "expression", "symbols": ["expression", "expression$ebnf$3", (lexer.has("minus") ? {type: "minus"} : minus), "expression$ebnf$4", "term"], "postprocess": ([fst,,,,snd]) => fst - snd},
    {"name": "expression", "symbols": ["term"], "postprocess": ([term]) => term},
    {"name": "term$ebnf$1", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "term$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "term$ebnf$2", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "term$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "term", "symbols": ["term", "term$ebnf$1", (lexer.has("times") ? {type: "times"} : times), "term$ebnf$2", "factor"], "postprocess": ([fst,,,,snd]) => fst * snd},
    {"name": "term$ebnf$3", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "term$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "term$ebnf$4", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "term$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "term", "symbols": ["term", "term$ebnf$3", (lexer.has("over") ? {type: "over"} : over), (lexer.has("over") ? {type: "over"} : over), "term$ebnf$4", "factor"], "postprocess": ([fst,,,,,snd]) => Math.trunc(fst / snd)},
    {"name": "term$ebnf$5", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "term$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "term$ebnf$6", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "term$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "term", "symbols": ["term", "term$ebnf$5", (lexer.has("over") ? {type: "over"} : over), "term$ebnf$6", "factor"], "postprocess": ([fst,,,,snd]) => fst / snd},
    {"name": "term", "symbols": [(lexer.has("minus") ? {type: "minus"} : minus), "factor"], "postprocess": ([,fst]) => (-1) * fst},
    {"name": "term", "symbols": ["factor"], "postprocess": ([factor]) => factor},
    {"name": "factor", "symbols": [(lexer.has("number") ? {type: "number"} : number)], "postprocess": ([number]) => +number},
    {"name": "factor$ebnf$1", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "factor$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "factor$ebnf$2", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "factor$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "factor", "symbols": [(lexer.has("lparen") ? {type: "lparen"} : lparen), "factor$ebnf$1", "conditional", "factor$ebnf$2", (lexer.has("rparen") ? {type: "rparen"} : rparen)], "postprocess": ([,,conditional,,]) => conditional},
    {"name": "factor", "symbols": ["fun"], "postprocess": ([fun]) => fun},
    {"name": "fun$ebnf$1", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "fun$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "fun", "symbols": [(lexer.has("func") ? {type: "func"} : func), (lexer.has("lparen") ? {type: "lparen"} : lparen), "fun$ebnf$1", (lexer.has("rparen") ? {type: "rparen"} : rparen)], "postprocess": ([fun,,,]) => mathFunctions.get(fun.value).apply(null)},
    {"name": "fun$ebnf$2", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "fun$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "fun$ebnf$3", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "fun$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "fun", "symbols": [(lexer.has("func") ? {type: "func"} : func), (lexer.has("lparen") ? {type: "lparen"} : lparen), "fun$ebnf$2", "params", "fun$ebnf$3", (lexer.has("rparen") ? {type: "rparen"} : rparen)], "postprocess": ([fun,,,params,,]) => mathFunctions.get(fun.value).apply(null, params)},
    {"name": "params", "symbols": ["m"], "postprocess": ([m]) => m},
    {"name": "m$ebnf$1", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "m$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "m$ebnf$2", "symbols": [(lexer.has("whitespace") ? {type: "whitespace"} : whitespace)], "postprocess": id},
    {"name": "m$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "m", "symbols": ["conditional", "m$ebnf$1", (lexer.has("comma") ? {type: "comma"} : comma), "m$ebnf$2", "m"], "postprocess": ([fst,,,,m]) => [fst].concat(m)},
    {"name": "m", "symbols": ["conditional"], "postprocess": ([fst]) => [fst]}
]
  , ParserStart: "line"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
